### ISSUE TITLE
core.http Action configuration breaks UI if timeout is entered

### ISSUE THREAD

**Issue by sk8erwitskil** [StackStorm/st2web#986]
## Problem
When trying to modify the timeout on the core.http Action configuration page, as soon as you enter in a value into the timeout text field the UI breaks.

## Error
```
TypeError: value.startsWith is not a function
    at ActionsDetails.isExpression (main.js:1:7371)
    at ActionsDetails.render (main.js:1:12925)
```

## Reproduce
Go go `/#/actions/core.http` and enter in any number into the `timeout` field.

**Comment by armab** [comment]
Thanks for submitting the bug report, @sk8erwitskil!
